### PR TITLE
fix: Stripping dm rooms successfully

### PR DESCRIPTION
**Pull request by Demolemon11**
I finally gave up on doing the dm rooms stripping in `sliding_sync.rs`, it was too primitive and not good for maintenance, since there could be all kinds of room types later on.

I managed to copy it to `Client` in `rooms_list.rs` via `get_client()` in `sliding_sync.rs`, and I did it through `Runtime` in tokio to `handle_event` method under `Widget` Trait to asynchronously determine the dm rooms in sync function (modify one of the variants of `RoomsListUpdate` enum), and stripped them to `PeopleList` type, which is almost the same as `RoomsList`. But there are still some minor problems with makepad.

I debugged it for a long time. Finally I noticed that only one of the two types (`PeopleList` & `RoomsList`) can display.

### CODE REVIEW

**Comment by kevinaboos** [comment]
oops, you've pushed up your username & passsword. I suggest you force push this commit to remove that ASAP.

**Comment by Demolemon11** [comment]
> oops, you've pushed up your username & passsword. I suggest you force push this commit to remove that ASAP.

I have deleted `login.toml`, sorry : )

**Review by Demolemon11 — COMMENTED** [review]
Irrelevant files deleted

**Review by Demolemon11 — COMMENTED** [review]
viewed

**Comment by Demolemon11** [comment]
please review : )

**Comment by kevinaboos** [comment]
Hi @Demolemon11, not sure why you closed this, but no worries.

Note that you did not actually _force push_ the branch, so the commits where you added and removed your pw are still visible.

**Comment by Demolemon11** [comment]
> Hi @Demolemon11, not sure why you closed this, but no worries.
> 
> Note that you did not actually _force push_ the branch, so the commits where you added and removed your pw are still visible.

Please allow me to ask an unrelated question, is `project-robius` financed?

**Pull request closed without merging**
