### PR TITLE
Working on the search bar (#123)

### PR DESCRIPTION
**Pull request by tyreseluo**
Implemented:
1. Currently implemented to show a small ❌ when the user has input, and delete the entered content when clicked on.
image
3. placeholder functionality.
image

Not implemented:
Currently there is no search function implemented, @kevinaboos do you have any good method for passing parameters between two sibling components? The source code is located in /src/home/rooms_sidebar.rs, the components <RoomsList> and <SearchBar>

My current thinking is that when the user enters something in the search bar, the value is passed to the rooms list, and then the rooms list does the filtering.

### CODE REVIEW

**Comment by tyreseluo** [comment]
Or what needs to be improved about the current component. In the meantime, I'm currently ramping up my makepad studies and hope to make some contributions!

**Comment by kevinaboos** [comment]
Looks great, thanks for the initial contribution! 

> Currently there is no search function implemented, @kevinaboos do you have any good method for passing parameters between two sibling components?

Yes, fortunately Makepad supports this with its Actions concept. The basic idea is that one widget "emits" an action, and then any other widgets (anywhere within the app) can handle that action as part of the event handler. You can see some other examples in Robrix already, look for `cx.widget_action()` which produces/emits a new action, and then look for `.as_widget_action()` which attempts to handle an action. 


> My current thinking is that when the user enters something in the search bar, the value is passed to the rooms list, and then the rooms list does the filtering.

Yep, that should definitely work, and actions will help you facilitate that control flow.

**Comment by tyreseluo** [comment]
ok, thanks for the suggestion, I'll try it!

**Comment by tyreseluo** [comment]
oops! Currently combining and merge difficulties, I need to check.

**Pull request closed without merging**
