### PR TITLE
Implement replying to messages and reply previews

### PR DESCRIPTION
**Pull request by fmzbl**
implements:
- sending replies to messages #83 
- showing preview of the replied message #82 

still fixing some small todos and styles, but core functionality is done.

----------------------

[From Kevin]: before this gets merged in, we need to:

- [x] fix reply button styling and direction
- [x] fix the issues with usernames and message content not displaying, which is related to how Robrix carefully caches already-drawn timeline events. I'll tackle this shortly.
- [ ] fix remaining to-dos about styling buttons and other UI items.
- [ ] fix horizontal alignment of Condensed* messages -- they're no longer left-aligned with regular messages
- [x] set `cursor: Hand` for the `ReplyingPreview` widget to make it more obvious that they're clickable w/ actions.
    * Huh, this was actually already set, but it's not displaying the cursor as intended. Probably an issue with PortalList or Makepad's hover actions, which have been fixed in a recent version that Robrix hasn't yet upgraded to.
- [ ] for the action `ReplyPreviewClicked`, we need a few things:
    - [ ] include the unique event ID to handle the case where the replied-to message hasn't been retrieved from the server (via pagination) and isn't yet locally available.
         * This is actually quite complex to deal with, so maybe we can save it for a future issue, and for now we can simply log a warning that says something like "TODO: jumping back to a replied-to message that isn't yet locally retrieved is currently unsupported"
    - [ ] a smooth scrolling action that scrolls upwards to that message rather than an abrupt jump (Makepad's PortalList may not yet support this?)
    - [ ] highlighting or temporarily flashing the background (maybe light blue or green) to indicate which specific message was the one being shown in the just-clicked `ReplyingPreview`
- [x] fix avatar font sizing in `ReplyingPreview` to be properly scaled down.
- [ ] shift the inline reply preview (the one above the message) to the right a bit such that the vertical bar is aligned with the middle of the avatar picture.
- [ ] Refactor the `populate_message*` logic such that it can be easily re-used for populating the content of a `ReplyingPreview`.  I will also tackle this.

### CODE REVIEW

**Comment by kevinaboos** [comment]
thanks! let me know when you're done so I can review it (and you can also request a review directly from me here too)

**Comment by fmzbl** [comment]
there are a few stuff that may seem ugly: they probably are. using the matrix sdk/api was a real pain, and took me a lot of time and refactoring to get something that works and tries to fit with the rest of the code.

**Comment by fmzbl** [comment]
i left an issue(#110) for adding the floating menus when we have support inside of makepad

**Comment by kevinaboos** [comment]
Thanks, this is an awesome start! I've cleaned up some unrelated formatting issues, fixed the reply button styling (with a new icon), and resolved the merge conflicts by merging in the latest changes from `main`.

In the future, kindly try to avoid making tons of formatting changes and committing them, as it makes it very difficult to review what's changed.

Before this gets merged in, we need to:
1. fix the issues with usernames and message content not displaying, which is related to how Robrix carefully caches already-drawn timeline events. I'll tackle this shortly.
2. fix remaining to-dos about styling buttons and things.
3. fix horizontal alignment of Condensed* messages -- they're not longer left-aligned with regular messages
4. set `cursor: Hand` for the `ReplyingPreview` widget to make it more obvious that they're clickable w/ actions.
5. for the action `ReplyPreviewClicked`, we need a few things:
    1. include the unique event ID to handle the case where the replied-to message hasn't been retrieved from the server (via pagination) and isn't yet locally available.
        * This is actually quite complex to deal with, so maybe we can save it for a future issue, and for now we can simply log a warning that says something like "TODO: jumping back to a replied-to message that isn't yet locally retrieved is currently unsupported"
    2. a smooth scrolling action that scrolls upwards to that message rather than an abrupt jump (Makepad's PortalList may not yet support this?)
    3. highlighting or temporarily flashing the background (maybe light blue or green) to indicate which specific message was the one being shown in the just-clicked `ReplyingPreview`
6. fix avatar font sizing in `ReplyingPreview` to be properly scaled down.
7. shift the inline reply preview (the one above the message) to the right a bit such that the vertical bar is aligned with the middle of the avatar picture.

**Comment by fmzbl** [comment]
> In the future, kindly try to avoid making tons of formatting changes and committing them, as it makes it very difficult to review what's changed. Also, please don't force-push any more commits as it will invalidate the review history here on github. thanks!

yeah, i tried to remove every formatting change that i saw. maybe we can have a `rustfmt.toml`?

**Comment by kevinaboos** [comment]
yea we'll definitely do that in the near future. That, and clippy lints.

**Comment by kevinaboos** [comment]
fixed the issue of message username/profile info not being properly populated.

**Comment by kevinaboos** [comment]
fixed all other non-UI issues.

**Review by kevinaboos — APPROVED** [review]
Thanks! I'm going to go ahead and merge this because it is in an acceptable state.

I will file a follow-up issue to track the remaining to-do items, and will also leave issues #82 and #83 open until those UI fixes are complete.

**Pull request merged**
